---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: build and push docker
  image: &plugin_docker plugins/docker:18.09.0
  settings:
    registry: quay.io
    repo: &image_path quay.io/suzuki_shunsuke/yamllint
    username: "suzuki_shunsuke+yamllint"
    password:
      from_secret: quayio_password
    tags:
    - "1.20.0__${DRONE_TAG##v}"
    - "1.20.0"
  when:
    event:
    - tag

- name: test to build docker
  image: *plugin_docker
  settings:
    registry: quay.io
    repo: *image_path
    dry_run: true
  when:
    event:
    - pull_request
    - push
