---
kind: pipeline
name: yamllint
platform:
  os: linux
  arch: amd64
steps:
- name: yamllint
  image: quay.io/suzuki_shunsuke/yamllint:1.20.0__1
  commands:
  - 'find . \( -name "*.yml" -o -name "*.yaml" \) -print0 | xargs -0 yamllint -c .yamllint.yml'

---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: build and push docker
  image: plugins/docker:18.09.2
  settings:
    registry: quay.io
    repo: &image_path quay.io/suzuki_shunsuke/yamllint
    username: "suzuki_shunsuke+yamllint"
    password:
      from_secret: quayio_password
    tags:
    - "1.23.0__${DRONE_TAG##v}"
    - "1.23.0"
  when:
    event:
    - tag

- name: test to build docker
  image: plugins/docker:18.09.2
  settings:
    registry: quay.io
    repo: *image_path
    dry_run: true
  when:
    event:
    - pull_request
    - push
